/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formwindow;

import static formwindow.RegexCheck.validateEmail;
import static formwindow.RegexCheck.validateFirstName;
import static formwindow.RegexCheck.validateLastName;
import static formwindow.RegexCheck.validatePassword;
import static formwindow.RegexCheck.validateUsername;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


/**
 *
 * @author Travis
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();     
    }

    
    public ImageIcon ic = new ImageIcon("resources/sprites/Space.gif");
    public boolean FNErr=true, LNErr=true, emailErr=true, UNErr=true,
            PW1Err=true, PW2Err=true;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   public void initComponents1(){ panel = new javax.swing.JPanel();}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        subheader = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        firstNameError = new javax.swing.JLabel();
        lastNameError = new javax.swing.JLabel();
        emailError = new javax.swing.JLabel();
        userNameError = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        password1label = new javax.swing.JLabel();
        password2label = new javax.swing.JLabel();
        password1Error = new javax.swing.JLabel();
        password2Error = new javax.swing.JLabel();
        errorBox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 0, 18));

        panel.setBackground(new java.awt.Color(2, 0, 33));
        panel.setFocusable(false);
        panel.setName(""); // NOI18N

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 0));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Space Invaders!!");
        header.setPreferredSize(new java.awt.Dimension(640, 50));
        header.setVerifyInputWhenFocusTarget(false);

        subheader.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        subheader.setForeground(new java.awt.Color(255, 255, 0));
        subheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subheader.setText("Please Enter Your Information to Register");
        subheader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        firstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 0));
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 0));
        lastNameLabel.setText("Last Name:");

        firstName.setBackground(panel.getBackground());
        firstName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 0));
        firstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });

        lastName.setBackground(panel.getBackground());
        lastName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 0));
        lastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });

        emailLabel.setBackground(panel.getBackground());
        emailLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 0));
        emailLabel.setText("Email Address:");

        userNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 0));
        userNameLabel.setText("User Name:");

        email.setBackground(panel.getBackground());
        email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 0));
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        userName.setBackground(panel.getBackground());
        userName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 0));
        userName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });

        register.setBackground(panel.getBackground());
        register.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 0));
        register.setText("Register!");
        register.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        back.setBackground(panel.getBackground());
        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 0));
        back.setText("Back to Menu");
        back.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));

        clear.setBackground(panel.getBackground());
        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 0));
        clear.setText("Clear Form");
        clear.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        firstNameError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        firstNameError.setForeground(new java.awt.Color(255, 255, 0));

        lastNameError.setBackground(panel.getBackground());
        lastNameError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lastNameError.setForeground(new java.awt.Color(255, 255, 0));

        emailError.setBackground(panel.getBackground());
        emailError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 255, 0));

        userNameError.setBackground(panel.getBackground());
        userNameError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userNameError.setForeground(new java.awt.Color(255, 255, 0));

        password1.setBackground(panel.getBackground());
        password1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 0));
        password1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        password1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                password1FocusLost(evt);
            }
        });

        password2.setBackground(panel.getBackground());
        password2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 0));
        password2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        password2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                password2FocusLost(evt);
            }
        });

        password1label.setBackground(panel.getBackground());
        password1label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password1label.setForeground(new java.awt.Color(255, 255, 0));
        password1label.setText("Password:");

        password2label.setBackground(panel.getBackground());
        password2label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password2label.setForeground(new java.awt.Color(255, 255, 0));
        password2label.setText("Retype Password:");

        password1Error.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        password1Error.setForeground(new java.awt.Color(255, 255, 0));

        password2Error.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password2Error.setForeground(new java.awt.Color(255, 255, 0));

        errorBox.setBackground(panel.getBackground());
        errorBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        errorBox.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstName)
                                    .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(password1label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(password2label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userName)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(password1)
                                    .addComponent(password2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(lastNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password1Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password2Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subheader, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password1Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password1label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password2Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password2label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String password1Input;
    public String password2Input;
    
    private void password2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password2FocusLost
        char[] input = password2.getPassword();
        password2Input="";
        for(int i=0;i<input.length;i++){
            password2Input+=input[i];
        }
        if((password1Input).equals(password2Input)){
            password2Error.setText("");
            password2.setBackground(panel.getBackground());
            PW2Err=false;
        }else{
            password2Error.setText("<html>*Must match <br/>previous password</html>");
            password2.setBackground(Color.red);
            PW2Err=true;
        }
    }//GEN-LAST:event_password2FocusLost

    private void password1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password1FocusLost

        char[] input = password1.getPassword();
        password1Input="";
        for(int i=0;i<input.length;i++){
            password1Input+=input[i];
        }
        if(validatePassword(password1Input)){
            password1Error.setText("");
            password1.setBackground(panel.getBackground());
            PW1Err=false;
        }else{
            password1Error.setText("<html>*Must contain atleast <br/>1 upper case, 1 lower case<br/> and 1 number</html>");
            password1.setBackground(Color.red);
            PW1Err=true;
        }
    }//GEN-LAST:event_password1FocusLost

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        firstName.setText("");
        firstNameError.setText(" ");
        firstName.setBackground(panel.getBackground());
        FNErr=true;

        lastName.setText("");
        lastNameError.setText(" ");
        lastName.setBackground(panel.getBackground());
        LNErr=true;

        email.setText("");
        emailError.setText(" ");
        email.setBackground(panel.getBackground());
        emailErr=true;

        userName.setText("");
        userNameError.setText(" ");
        userName.setBackground(panel.getBackground());
        UNErr=true;

        password1.setText("");
        password1Error.setText("");
        password1.setBackground(panel.getBackground());
        PW1Err=true;

        password2.setText("");
        password2Error.setText("");
        password2.setBackground(panel.getBackground());
        PW2Err=true;

        errorBox.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        if(!FNErr && !LNErr && !emailErr && !UNErr && !PW1Err && !PW2Err){
            errorBox.setText("Everything is Correct");
        }else{
            errorBox.setText("*Please correct the issues.");
        }
    }//GEN-LAST:event_registerActionPerformed

    private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost

        if(!validateUsername(userName.getText())){
            userNameError.setText("*Invalid");
            userName.setBackground(Color.red);
            UNErr=true;
        }else{
            userNameError.setText(" ");
            userName.setBackground(panel.getBackground());
            UNErr=false;
        }
    }//GEN-LAST:event_userNameFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(!validateEmail(email.getText())){
            emailError.setText("*Invalid");
            email.setBackground(Color.red);
            emailErr=true;
        }else{
            emailError.setText(" ");
            email.setBackground(panel.getBackground());
            emailErr=false;
        }
    }//GEN-LAST:event_emailFocusLost

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        // TODO add your handling code here:
        if(!validateLastName(lastName.getText())){
            lastNameError.setText("*Invalid");
            lastName.setBackground(Color.red);
            LNErr=true;
        }else{
            lastNameError.setText(" ");
            lastName.setBackground(panel.getBackground());
            LNErr=false;
        }
    }//GEN-LAST:event_lastNameFocusLost

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        // TODO add your handling code here:
        if(!validateFirstName(firstName.getText())){
            firstNameError.setText("*Invalid");
            firstName.setBackground(Color.red);
            FNErr=true;
        }else{
            firstNameError.setText(" ");
            firstName.setBackground(panel.getBackground());
            FNErr=false;
        }
    }//GEN-LAST:event_firstNameFocusLost

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

class BackgroundPanel extends  Registration{    
    // The Image to store the background image in.
    Image img;
    public BackgroundPanel(){
        // Loads the background image and stores in img object.
        img = Toolkit.getDefaultToolkit().createImage("resources/backgrounds/Space.gif");
    }
    @Override
    public void paint(Graphics g){
        // Draws the img to the BackgroundPanel.
        g.drawImage(img, 0, 0, null);
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
        
//        public void actionPerformed(ActionEvent buttonPress ) {
//		System.out.println("The Button Works!");//what the button says when clicked.
//	}
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel errorBox;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameError;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel header;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameError;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField password1;
    private javax.swing.JLabel password1Error;
    private javax.swing.JLabel password1label;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel password2Error;
    private javax.swing.JLabel password2label;
    private javax.swing.JButton register;
    private javax.swing.JLabel subheader;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameError;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
