/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.GutierrezLeonardo.CSC18B.SpaceInvaders;

import javax.swing.JOptionPane;

/**
 *
 * @author Leo
 */
public class ScoreScreen extends javax.swing.JFrame {

    /**
     * Creates new form ScoreScreen
     */
    public ScoreScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highScoreLabel = new javax.swing.JLabel();
        scorelabel1 = new javax.swing.JLabel();
        player1TextField = new javax.swing.JTextField();
        scoreLabel2 = new javax.swing.JLabel();
        scoreLabel3 = new javax.swing.JLabel();
        scoreLabel4 = new javax.swing.JLabel();
        scoreLabel5 = new javax.swing.JLabel();
        scoreLabel6 = new javax.swing.JLabel();
        scoreLabel7 = new javax.swing.JLabel();
        scoreLabel8 = new javax.swing.JLabel();
        scoreLabel9 = new javax.swing.JLabel();
        scoreLabel10 = new javax.swing.JLabel();
        player2TextField = new javax.swing.JTextField();
        player3TextField = new javax.swing.JTextField();
        player4TextField = new javax.swing.JTextField();
        player5TextField = new javax.swing.JTextField();
        player6TextField = new javax.swing.JTextField();
        player7TextField = new javax.swing.JTextField();
        player8TextField = new javax.swing.JTextField();
        player9TextField = new javax.swing.JTextField();
        player10TextField = new javax.swing.JTextField();
        playAgainButton = new javax.swing.JButton();
        ExitGameButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        instructionsMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        authorsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();
        exitGameMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setName("ScoreFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));

        highScoreLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        highScoreLabel.setText("HIGH SCORES");

        scorelabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scorelabel1.setText("00000");

        player1TextField.setEditable(false);
        player1TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player1TextField.setText("AAAAA");

        scoreLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel2.setText("00000");

        scoreLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel3.setText("00000");

        scoreLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel4.setText("00000");

        scoreLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel5.setText("00000");

        scoreLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel6.setText("00000");

        scoreLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel7.setText("00000");

        scoreLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel8.setText("00000");

        scoreLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel9.setText("00000");

        scoreLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        scoreLabel10.setText("00000");

        player2TextField.setEditable(false);
        player2TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player2TextField.setText("BBBBB");

        player3TextField.setEditable(false);
        player3TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player3TextField.setText("CCCCC");

        player4TextField.setEditable(false);
        player4TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player4TextField.setText("DDDDD");

        player5TextField.setEditable(false);
        player5TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player5TextField.setText("EEEEE");

        player6TextField.setEditable(false);
        player6TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player6TextField.setText("FFFFF");

        player7TextField.setEditable(false);
        player7TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player7TextField.setText("GGGGG");

        player8TextField.setEditable(false);
        player8TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player8TextField.setText("HHHHH");

        player9TextField.setEditable(false);
        player9TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player9TextField.setText("JJJJJ");

        player10TextField.setEditable(false);
        player10TextField.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        player10TextField.setText("KKKKK");

        playAgainButton.setText("Play Again");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        ExitGameButton.setText("Exit Game");
        ExitGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitGameButtonActionPerformed(evt);
            }
        });

        helpMenu.setText("Help");

        instructionsMenuItem.setText("Instructions");
        instructionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(instructionsMenuItem);

        jMenuBar1.add(helpMenu);

        aboutMenu.setText("About");

        authorsMenuItem.setText("Authors");
        authorsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorsMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(authorsMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutMenuItem);

        jMenuBar1.add(aboutMenu);

        exitMenu.setText("Exit");

        exitGameMenuItem.setText("Exit Game");
        exitGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameMenuItemActionPerformed(evt);
            }
        });
        exitMenu.add(exitGameMenuItem);

        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(playAgainButton)
                .addGap(104, 104, 104)
                .addComponent(ExitGameButton)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player9TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scorelabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scoreLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(highScoreLabel))
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(highScoreLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scorelabel1)
                    .addComponent(player1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel2)
                    .addComponent(player2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel3)
                    .addComponent(player3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel4)
                    .addComponent(player4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel5)
                    .addComponent(player5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel6)
                    .addComponent(player6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel7)
                    .addComponent(player7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel8)
                    .addComponent(player8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel9)
                    .addComponent(player9TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreLabel10)
                    .addComponent(player10TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton)
                    .addComponent(ExitGameButton))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"SPACE INVADERS:  This is a recreation of the classic game\n"
					+ "released in 1978.",
					"ABOUT",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void authorsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorsMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"         SPACE INVADERS         \n"
										    +  "                                \n"
										    +  "          Developed by          \n"
											+  "                                \n"
											+  "         Travis Hajagos         \n"
											+  "         Brian Warfield         \n"
											+  "         Leo Gutierrez          \n"
											+  "          David Silva             ",
											"THE AUTHORS",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_authorsMenuItemActionPerformed

    private void instructionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Scoring:\n 10 Front row  \n20 Second row  \n30 Third Row"
					+ "\nSpaceShip is ????   \nObject of the game to hit all the aliens before you run"
					+ "out of lives.  \nPlay as long as possible to get the high score. ",
					"INSTRUCTIONS",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_instructionsMenuItemActionPerformed

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("You have pressed the Play Again button");
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void ExitGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitGameButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitGameButtonActionPerformed

    private void exitGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitGameMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitGameButton;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem authorsMenuItem;
    private javax.swing.JMenuItem exitGameMenuItem;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel highScoreLabel;
    private javax.swing.JMenuItem instructionsMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JTextField player10TextField;
    private javax.swing.JTextField player1TextField;
    private javax.swing.JTextField player2TextField;
    private javax.swing.JTextField player3TextField;
    private javax.swing.JTextField player4TextField;
    private javax.swing.JTextField player5TextField;
    private javax.swing.JTextField player6TextField;
    private javax.swing.JTextField player7TextField;
    private javax.swing.JTextField player8TextField;
    private javax.swing.JTextField player9TextField;
    private javax.swing.JLabel scoreLabel10;
    private javax.swing.JLabel scoreLabel2;
    private javax.swing.JLabel scoreLabel3;
    private javax.swing.JLabel scoreLabel4;
    private javax.swing.JLabel scoreLabel5;
    private javax.swing.JLabel scoreLabel6;
    private javax.swing.JLabel scoreLabel7;
    private javax.swing.JLabel scoreLabel8;
    private javax.swing.JLabel scoreLabel9;
    private javax.swing.JLabel scorelabel1;
    // End of variables declaration//GEN-END:variables
}
